name: 'semantic versioning'
description: 'bump a version'

inputs:
  image_name:
    description: 'image name'
    required: false
    default: '.'
  docker_repo:
    description: 'docker repo'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
  - uses: 'actions/checkout@v3'
  
  - id: 'auth'
    name: 'Authenticate to Google Cloud'
    uses: 'google-github-actions/auth@v0'
    with:
      token_format: 'access_token'
      workload_identity_provider: 'projects/474377433429/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider'
      service_account: 'github-actions@ltx-research.iam.gserviceaccount.com'
  
  - name: sementic versioning
    id: semver
    shell: bash
    run: |
      curr_tag=$(gcloud container images list-tags ${{ inputs.image_name }}/${{ inputs.docker_repo }} --filter="tags:*" | awk '{print $2}' | head -2 | tail -1)
      new_tag=$(${GITHUB_WORKSPACE}/.github/script.sh)
      echo "::set-output name=new_tag::$(echo $new_tag)"
      
outputs:
  new_tag:
    description: "new tag"
    value: ${{ steps.semver.outputs.new_tag }}
      
      
      
    
